
module.exports = {
	env: { es2020: true },
	extends: [ "eslint:recommended", "mdcs" ],
	parserOptions: { ecmaVersion: 2020 },
	rules: {
		"arrow-body-style": [ "error", "as-needed" ],
		"arrow-parens": [ "error", "as-needed" ],
		"comma-dangle": [ "error", "always-multiline" ],
		"no-console": 0,
		"no-constant-condition": 0,
		"no-duplicate-imports": [ "error" ],
		"no-extra-parens": [ "error" ],
		"no-multiple-empty-lines": [ "error", { max: 1 } ],
		"no-self-assign": [ "error", { props: false } ],
		"no-unused-vars": [ "error", { ignoreRestSiblings: true } ],
		"no-var": [ "error" ],
		"object-shorthand": [ "error" ],
		"prefer-arrow-callback": [ "error" ],
		"prefer-const": [ "error" ],
		"quote-props": [ "error", "as-needed" ],
		"spaced-comment": [ "error", "always", { exceptions: [ "/" ] } ],
		curly: [ "error", "multi" ],
		eqeqeq: [ "error" ],
		quotes: [ "error", "double" ],
		strict: [ "error" ],
	},
};
